---
# tasks file for dnf

- name: Install some common dnf repositories
  become: true
  ansible.builtin.dnf:
    name:
      - epel-release
      - elrepo-release
    state: present

- name: Install some common dnf packages
  become: true
  ansible.builtin.dnf:
    name:
      - unzip
      - make
      - htop
    state: present

- name: Install C++ dnf packages
  become: true
  ansible.builtin.dnf:
    name:
      - clang
      - clang-tools-extra
      - cmake
    state: present
