---
# tasks file for dnf

- name: Install some common dnf repositories
  become: true
  ansible.builtin.dnf:
    name:
      - epel-release
      - elrepo-release
    state: present

- name: Install some common dnf packages
  become: true
  ansible.builtin.dnf:
    name:
      - unzip
      - make
      - htop
    state: present

- name: Install C++ dnf packages
  become: true
  ansible.builtin.dnf:
    name:
      - clang
      - clang-tools-extra
      - cmake
      - gdb
    state: present

- name: Install QEMU
  become: true
  ansible.builtin.dnf:
    name:
      - qemu-kvm
      - qemu-img
      - virt-install
      - libvirt
      - tigervnc
      - libguestfs
      - guestfs-tools
      - flex
      - bison
      - elfutils-libelf-devel
      - openssl-devel
    state: present

- name: Install observability tools
  become: true
  ansible.builtin.dnf:
    name:
      - perf
      - sysstat
      - util-linux
    state: present
