---
# tasks file for firecracker

- name: Check firecracker installed
  stat:
    path: "~/firecracker/release-v{{ version }}-{{ ansible_architecture }}"
  register: firecracker

- name: Create firecracker directory
  ansible.builtin.file:
    path: ~/firecracker
    state: directory
    mode: '0755'

- name: Download firecracker
  ansible.builtin.unarchive:
    src: "https://github.com/firecracker-microvm/firecracker/releases/download/v{{ version }}/firecracker-v{{ version }}-{{ ansible_architecture }}.tgz"
    dest: ~/firecracker
    remote_src: yes
  register: firecracker_download
  when: not firecracker.stat.exists

- name: Create firecracker binary directory
  ansible.builtin.file:
    path: ~/firecracker/bin
    state: directory
    mode: '0755'

- name: Create a symbolic link for firecracker
  ansible.builtin.file:
    src: "~/firecracker/release-v{{ version }}-{{ ansible_architecture }}/firecracker-v{{ version }}-{{ ansible_architecture }}"
    dest: ~/firecracker/bin/firecracker
    state: link

- name: Download kernel binary
  ansible.builtin.get_url:
    url: "https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/{{ ansible_architecture }}/kernels/vmlinux.bin"
    dest: ~/firecracker/vmlinux.bin
    mode: 0644

- name: Download root fs
  ansible.builtin.get_url:
    url: "https://s3.amazonaws.com/spec.ccfc.min/ci-artifacts/disks/{{ ansible_architecture }}/ubuntu-18.04.ext4"
    dest: ~/firecracker/ubuntu-18.04.ext4
    mode: 0644

- name: Download root fs ssh keys
  ansible.builtin.get_url:
    url: "https://s3.amazonaws.com/spec.ccfc.min/ci-artifacts/disks/{{ ansible_architecture }}/ubuntu-18.04.id_rsa"
    dest: ~/firecracker/ubuntu-18.04.id_rsa
    mode: 0400

- name: Copy vm bootstrap script
  ansible.builtin.copy:
    src: start_vm.sh
    dest: ~/firecracker/start_vm.sh

- name: Add firecracker to PATH
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: PATH="$PATH:~/firecracker/bin"
    state: present
  when: firecracker_download.changed

- name: Add FIRECRACKER_SOCKET env variable
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: FIRECRACKER_SOCKET="$HOME/firecracker/firecracker.socket"
    state: present
  when: firecracker_download.changed

- name: Add FIRECRACKER_LOGFILE env variable
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: FIRECRACKER_LOGFILE="$HOME/firecracker/firecracker.log"
    state: present
  when: firecracker_download.changed

- name: Create firecracker log file
  ansible.builtin.file:
    path: ~/firecracker/firecracker.log
    state: file
    mode: '0644'
