version = 2
disabled_plugins = ["io.containerd.grpc.v1.cri"]
root = "{{ ansible_facts['env']['HOME'] }}/.firecracker/var/lib/firecracker-containerd/containerd"
state = "{{ ansible_facts['env']['HOME'] }}/.firecracker/run/firecracker-containerd"
[grpc]
  address = "{{ ansible_facts['env']['HOME'] }}/.firecracker/run/firecracker-containerd/containerd.sock"
[plugins]
  [plugins."io.containerd.snapshotter.v1.devmapper"]
    pool_name = "fc-dev-thinpool"
    base_image_size = "10GB"
    root_path = "{{ ansible_facts['env']['HOME'] }}/.firecracker/var/lib/firecracker-containerd/snapshotter/devmapper"

[debug]
  level = "debug"
