---

- hosts: workstations
  roles:
    - dnf
    - asdf
    - miniconda
    - rootless-podman
    - rootless-docker
    - firecracker
    - firecracker-containerd

- hosts: rootless-workstations
  roles:
    - asdf
    - miniconda
    - firecracker

- hosts: test
  roles:
    - firecracker
    - firecracker-containerd
