---

- hosts: workstations
  roles:
    - dnf
    - vscode
    - asdf
    - miniconda
    - rust
    - rootless-podman
    - rootless-docker
    - firecracker
    - local-k8s
    - stargz

- hosts: rootless-workstations
  roles:
    - asdf
    - miniconda
    - rust
    - firecracker

- hosts: k8s-master
  roles:
    #- rootless-docker
    - k8s

- hosts: k8s-worker
  roles:
    #- rootless-docker
    - k8s

- hosts: test
  roles:
    - dnf
