---

- hosts: workstations
  roles:
    - dnf
    - vscode
    - asdf
    - miniconda
    - rust
    - rootless-podman
    - rootless-docker
    - firecracker
    - local-k8s
    - stargz

- hosts: rootless-workstations
  roles:
    - asdf
    - miniconda
    - rust
    - firecracker

- hosts: test
  roles:
    - stargz
